[2024-10-02T14:41:06.681+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_sac_pipeline.sac_to_s3 manual__2024-10-02T14:40:55.570680+00:00 [queued]>
[2024-10-02T14:41:06.692+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_sac_pipeline.sac_to_s3 manual__2024-10-02T14:40:55.570680+00:00 [queued]>
[2024-10-02T14:41:06.693+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-10-02T14:41:06.708+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): sac_to_s3> on 2024-10-02 14:40:55.570680+00:00
[2024-10-02T14:41:06.716+0000] {standard_task_runner.py:57} INFO - Started process 52 to run task
[2024-10-02T14:41:06.722+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_sac_pipeline', 'sac_to_s3', 'manual__2024-10-02T14:40:55.570680+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/sac_dag.py', '--cfg-path', '/tmp/tmpbno3blya']
[2024-10-02T14:41:06.726+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask sac_to_s3
[2024-10-02T14:41:06.800+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_sac_pipeline.sac_to_s3 manual__2024-10-02T14:40:55.570680+00:00 [running]> on host aff75d163634
[2024-10-02T14:41:06.952+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Biokpor Solomon' AIRFLOW_CTX_DAG_ID='etl_sac_pipeline' AIRFLOW_CTX_TASK_ID='sac_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T14:40:55.570680+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-02T14:40:55.570680+00:00'
[2024-10-02T14:41:07.247+0000] {logging_mixin.py:151} INFO - [Errno 2] No such file or directory: '/opt/***/fastfashion/sacraw.csv'
[2024-10-02T14:41:07.247+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-10-02T14:41:07.265+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=etl_sac_pipeline, task_id=sac_to_s3, execution_date=20241002T144055, start_date=20241002T144106, end_date=20241002T144107
[2024-10-02T14:41:07.334+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-10-02T14:41:07.369+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
